# Generated by Django 4.0.6 on 2022-08-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerstandard',
            name='name',
            field=models.CharField(default='PC Standard', max_length=255),
        ),
        migrations.AlterField(
            model_name='computerstandard',
            name='processor',
            field=models.CharField(default='3.1 GHz', max_length=100),
        ),
    ]
