# Generated by Django 4.0.6 on 2022-08-27 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_computerstandard_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerDeluxe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('name', models.CharField(default='PC Deluxe', max_length=255)),
                ('processor', models.CharField(default='4.5 GHz', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonitorCRT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pixQty', models.IntegerField(max_length=1)),
                ('name', models.CharField(default='CRT 21', max_length=255)),
                ('size', models.CharField(default='21', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonitorFlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pixQty', models.IntegerField(max_length=1)),
                ('name', models.CharField(default='Flat 19', max_length=255)),
                ('size', models.CharField(default='19', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
