# Generated by Django 4.0.6 on 2022-08-27 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_computerdeluxe_monitorcrt_monitorflat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorcrt',
            name='pixQty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='monitorflat',
            name='pixQty',
            field=models.IntegerField(),
        ),
    ]
