# Generated by Django 4.0.6 on 2022-08-27 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_pixqty_monitorcrt_picqty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerdeluxe',
            name='master_pr',
            field=models.CharField(default='Test', max_length=100),
        ),
        migrations.AddField(
            model_name='computerstandard',
            name='master_pr',
            field=models.CharField(default='Test', max_length=100),
        ),
        migrations.AddField(
            model_name='monitorcrt',
            name='master_pr',
            field=models.CharField(default='Test', max_length=100),
        ),
        migrations.AddField(
            model_name='monitorflat',
            name='master_pr',
            field=models.CharField(default='Test', max_length=100),
        ),
    ]
