# Generated by Django 4.0.6 on 2022-08-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_computerdeluxe_master_pr_computerstandard_master_pr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerdeluxe',
            name='name',
            field=models.CharField(default='PC Deluxe.', max_length=255),
        ),
    ]
