# Generated by Django 4.0.6 on 2022-08-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_computerdeluxe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerdeluxe',
            name='master_pr',
            field=models.CharField(default='Test1', max_length=100),
        ),
        migrations.AlterField(
            model_name='computerstandard',
            name='master_pr',
            field=models.CharField(default='Test1', max_length=100),
        ),
        migrations.AlterField(
            model_name='monitorcrt',
            name='master_pr',
            field=models.CharField(default='Test1', max_length=100),
        ),
        migrations.AlterField(
            model_name='monitorflat',
            name='master_pr',
            field=models.CharField(default='Test1', max_length=100),
        ),
    ]
