# Generated by Django 4.0.6 on 2022-10-03 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_computerdeluxe_master_pr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dataType', models.CharField(max_length=50)),
                ('mlclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.mlclass')),
            ],
        ),
    ]
