# Generated by Django 4.0.6 on 2022-10-03 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_mlclass_attribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlclass',
            name='size',
        ),
    ]
