# Generated by Django 4.1.2 on 2022-10-10 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_mlclass_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PTname', models.CharField(default='', max_length=200, verbose_name='name')),
            ],
        ),
        migrations.RemoveField(
            model_name='computerdeluxe',
            name='id',
        ),
        migrations.RemoveField(
            model_name='computerdeluxe',
            name='master_pr',
        ),
        migrations.RemoveField(
            model_name='computerdeluxe',
            name='name',
        ),
        migrations.RemoveField(
            model_name='computerdeluxe',
            name='price',
        ),
        migrations.RemoveField(
            model_name='computerdeluxe',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='computerstandard',
            name='id',
        ),
        migrations.RemoveField(
            model_name='computerstandard',
            name='master_pr',
        ),
        migrations.RemoveField(
            model_name='computerstandard',
            name='name',
        ),
        migrations.RemoveField(
            model_name='computerstandard',
            name='price',
        ),
        migrations.RemoveField(
            model_name='computerstandard',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='monitorcrt',
            name='id',
        ),
        migrations.RemoveField(
            model_name='monitorcrt',
            name='master_pr',
        ),
        migrations.RemoveField(
            model_name='monitorcrt',
            name='name',
        ),
        migrations.RemoveField(
            model_name='monitorcrt',
            name='picQty',
        ),
        migrations.RemoveField(
            model_name='monitorcrt',
            name='size',
        ),
        migrations.RemoveField(
            model_name='monitorflat',
            name='id',
        ),
        migrations.RemoveField(
            model_name='monitorflat',
            name='master_pr',
        ),
        migrations.RemoveField(
            model_name='monitorflat',
            name='name',
        ),
        migrations.RemoveField(
            model_name='monitorflat',
            name='picQty',
        ),
        migrations.RemoveField(
            model_name='monitorflat',
            name='size',
        ),
        migrations.AddField(
            model_name='computerdeluxe',
            name='CDname',
            field=models.CharField(default='PC Deluxe.', max_length=255, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='computerdeluxe',
            name='CDprocessor',
            field=models.CharField(default='4.5 GHz', max_length=100, verbose_name='processor'),
        ),
        migrations.AddField(
            model_name='computerstandard',
            name='CSname',
            field=models.CharField(default='PC Standard', max_length=255, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='computerstandard',
            name='CSprocessor',
            field=models.CharField(default='3.1 GHz', max_length=100, verbose_name='processor'),
        ),
        migrations.AddField(
            model_name='monitorcrt',
            name='MCname',
            field=models.CharField(default='CRT 21', max_length=255, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='monitorcrt',
            name='MCsize',
            field=models.CharField(default='21', max_length=50, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='monitorflat',
            name='MFsize',
            field=models.CharField(default='19', max_length=50, verbose_name='size'),
        ),
        migrations.AddField(
            model_name='monitorflat',
            name='MMname',
            field=models.CharField(default='Flat 19', max_length=255, verbose_name='name'),
        ),
        migrations.CreateModel(
            name='ComputerModel',
            fields=[
                ('producttype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.producttype')),
                ('CMprocessor', models.CharField(default='', max_length=100, verbose_name='processor')),
                ('CMprice', models.DecimalField(decimal_places=2, default='', max_digits=9, verbose_name='price')),
            ],
            bases=('product.producttype',),
        ),
        migrations.CreateModel(
            name='MonitorModel',
            fields=[
                ('producttype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.producttype')),
                ('MMsize', models.CharField(default='', max_length=50, verbose_name='size')),
                ('MMpicQty', models.IntegerField(default='', verbose_name='picQty')),
            ],
            bases=('product.producttype',),
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='MLClass',
        ),
        migrations.AddField(
            model_name='computerdeluxe',
            name='computermodel_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.computermodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computerstandard',
            name='computermodel_ptr',
            field=models.OneToOneField(auto_created=True, default='None', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.computermodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitorcrt',
            name='monitormodel_ptr',
            field=models.OneToOneField(auto_created=True, default=2, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.monitormodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitorflat',
            name='monitormodel_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.monitormodel'),
            preserve_default=False,
        ),
    ]
