# Generated by Django 4.0.6 on 2022-08-27 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mltool', '0002_alter_computerstandard_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComputerStandard',
        ),
    ]
