# Generated by Django 4.0.2 on 2022-10-23 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clabject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('potency', models.CharField(max_length=255)),
                ('instanceOf', models.ForeignKey(blank=True, default='None', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance', to='mltoolapp.clabject')),
                ('mldiagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mldiagram', to='mltoolapp.mldiagram')),
                ('subclassOf', models.ForeignKey(blank=True, default='None', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subclass', to='mltoolapp.clabject')),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('potency', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[('STRING', 'Text input'), ('INT', 'Number input'), ('DOUBLE', 'Decimal number'), ('DATE', 'Date input')], help_text='Data type', max_length=255)),
                ('value', models.CharField(blank=True, default='null', max_length=255, null=True)),
                ('clabject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mltoolapp.clabject')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
