# Generated by Django 4.0.2 on 2022-10-17 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clabject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('potency', models.CharField(max_length=255)),
                ('instanceOf', models.ForeignKey(blank=True, default='None', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance', to='mltoolapp.clabject')),
                ('subclassOf', models.ForeignKey(blank=True, default='None', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subclass', to='mltoolapp.clabject')),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('potency', models.CharField(max_length=255)),
                ('data_type', models.CharField(default='Null', max_length=255)),
                ('clabject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mltoolapp.clabject')),
            ],
        ),
    ]
