# Generated by Django 4.0.2 on 2022-10-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mltoolapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='value',
            field=models.CharField(blank=True, default='null', max_length=255, null=True),
        ),
    ]
