# Generated by Django 4.0.2 on 2022-10-17 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mltoolapp', '0002_attribute_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ['name']},
        ),
    ]
