# Generated by Django 4.1.2 on 2022-10-14 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mltoolapp', '0002_alter_clabject_instanceof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clabject',
            name='instanceOf',
        ),
        migrations.AddField(
            model_name='clabject',
            name='clabject',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classobject', to='mltoolapp.clabject'),
        ),
        migrations.AddField(
            model_name='clabject',
            name='subclassOf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subclass', to='mltoolapp.clabject'),
        ),
    ]
