# Generated by Django 4.1.2 on 2022-10-14 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mltoolapp', '0003_remove_clabject_instanceof_clabject_clabject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clabject',
            name='clabject',
            field=models.OneToOneField(default='None', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classobject', to='mltoolapp.clabject'),
        ),
        migrations.AlterField(
            model_name='clabject',
            name='subclassOf',
            field=models.ForeignKey(default='None', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subclass', to='mltoolapp.clabject'),
        ),
    ]
