# Generated by Django 4.1.2 on 2022-10-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mltoolapp', '0005_alter_clabject_clabject_alter_clabject_subclassof'),
    ]

    operations = [
        migrations.AddField(
            model_name='clabject',
            name='instanceOf',
            field=models.ManyToManyField(blank=True, default='None', null=True, related_name='instance', to='mltoolapp.clabject'),
        ),
    ]
